package com.rd.rd_app.ui.theme

import androidx.compose.ui.graphics.Color

// Tech Blue – Light theme
val LightPrimary = Color(0xFF1976D2)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBBDEFB)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF455A64)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCFD8DC)
val LightOnSecondaryContainer = Color(0xFF0D1B2A)
val LightTertiary = Color(0xFF00796B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFB2DFDB)
val LightOnTertiaryContainer = Color(0xFF00201B)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF5F7FA)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFF5F7FA)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE3E8F0)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightInverseSurface = Color(0xFF2F3033)
val LightInverseOnSurface = Color(0xFFF1F0F4)
val LightInversePrimary = Color(0xFF90CAF9)
val LightSurfaceTint = Color(0xFF1976D2)

// Tech Blue – Dark theme
val DarkPrimary = Color(0xFF42A5F5)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF0D47A1)
val DarkOnPrimaryContainer = Color(0xFFBBDEFB)
val DarkSecondary = Color(0xFFB0BEC5)
val DarkOnSecondary = Color(0xFF1C313A)
val DarkSecondaryContainer = Color(0xFF37474F)
val DarkOnSecondaryContainer = Color(0xFFCFD8DC)
val DarkTertiary = Color(0xFF80CBC4)
val DarkOnTertiary = Color(0xFF003731)
val DarkTertiaryContainer = Color(0xFF005048)
val DarkOnTertiaryContainer = Color(0xFFB2DFDB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF15171A)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF15171A)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF37474F)
val DarkOnSurfaceVariant = Color(0xFFB0BEC5)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInverseOnSurface = Color(0xFF1C313A)
val DarkInversePrimary = Color(0xFF1976D2)
val DarkSurfaceTint = Color(0xFF42A5F5)
