package com.rd.rd_app.ui.theme

import androidx.compose.ui.graphics.Color

// ── Tech Blue · Light theme ──
val LightPrimary = Color(0xFF1565C0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF1C446B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD4E3FF)
val LightOnSecondaryContainer = Color(0xFF001C37)
val LightTertiary = Color(0xFF176A92)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC0E8FF)
val LightOnTertiaryContainer = Color(0xFF001E2D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7F9FF)
val LightOnBackground = Color(0xFF181C20)
val LightSurface = Color(0xFFF7F9FF)
val LightOnSurface = Color(0xFF181C20)
val LightSurfaceVariant = Color(0xFFE0E3EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightInverseSurface = Color(0xFF2D3035)
val LightInverseOnSurface = Color(0xFFEEF1F6)
val LightInversePrimary = Color(0xFFA0CAFD)
val LightSurfaceTint = Color(0xFF1565C0)

// ── Tech Blue · Dark theme ──
val DarkPrimary = Color(0xFFA0CAFD)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF0D47A1)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFB6CAE5)
val DarkOnSecondary = Color(0xFF1E3146)
val DarkSecondaryContainer = Color(0xFF35485F)
val DarkOnSecondaryContainer = Color(0xFFD4E3FF)
val DarkTertiary = Color(0xFF84CFF2)
val DarkOnTertiary = Color(0xFF003545)
val DarkTertiaryContainer = Color(0xFF004C63)
val DarkOnTertiaryContainer = Color(0xFFC0E8FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF101316)
val DarkOnBackground = Color(0xFFE0E3E8)
val DarkSurface = Color(0xFF101316)
val DarkOnSurface = Color(0xFFE0E3E8)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkInverseSurface = Color(0xFFE0E3E8)
val DarkInverseOnSurface = Color(0xFF2D3035)
val DarkInversePrimary = Color(0xFF1565C0)
val DarkSurfaceTint = Color(0xFFA0CAFD)
